site_name: Tech Interview Guide

theme:
  name: material
  features:
    - navigation.expand
      - navigation.sections
      - navigation.prune
      - navigation.indexes
      - content.code.copy
  palette:
    scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode

extra_css:
  - extra.css
extra_javascript:
  - extra.js

nav:
  - Home: index.md

  - .NET:
      - C#:
          - Basics: Dotnet/csharp/basics.md
          - OOP Concepts: Dotnet/csharp/oop.md
          - Advanced Topics: Dotnet/csharp/advanced.md
  - Angular:
      - Fundamentals: Angular/fundamentals.md
      - Forms: Angular/forms.md
      - Migration Guide: Angular/migration.md
  - React:
      - Hooks: React/hooks.md
      - State Management: React/state.md
  - Project Management:
      - Jira:
          - Basics: Poject_Management/Jira/basics.md
  - Cloud:
      - Azure:
          - IASS_PASS_SAAS: Cloud/Azure/IAAS_PASS_SAAS.md
          - DTU_EDTU: Cloud/Azure/DTU_EDTU.md
          - AzureFunctions: Cloud/Azure/AzureFunctions.md
          - AzureStorage: Cloud/Azure/Azure_storage.md
          - AzureCosmosDB: Cloud/Azure/Azure_Cosmos_DB.md
          - AzureFabricandMicroServices: Cloud/Azure/Azure_Fabric_microservices.md
          - AzureTables: Cloud/Azure/Azure_Tables.md
          - AzureBlobs(block,append,page): Cloud/Azure/Azure_blobs(block,append,page).md
          - Azure_Queues: Cloud/Azure/Azure_Queues(Azure Queues , visibility timeouts ,Peek & De-Queue).md
          - Azure_Services: Cloud/Azure/Azure_Services(App services and Cloud services).md
          - Azure_WebJobs: Cloud/Azure/Azure_WebJobs(WebJob and background processing.).md
  - Scenarios:
      - Legacy Migration: Scenarios/migration.md
      - Real-World QA: Scenarios/realworld.md
